spring:
  application:
    name: budgets
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://root:HvItAsyneHVgnydtBGYjNzEunyRapFrF@viaduct.proxy.rlwy.net:18638/railway
    username: root
    password: HvItAsyneHVgnydtBGYjNzEunyRapFrF
    jpa:
      hibernate:
        ddl-auto: none
  cloud:
    config:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: https://budget-wise-discovery-server-production.up.railway.app/eureka/
server:
  port: ${PORT}
application:
  config:
    expenses-url: https://budgetwise-expenses-production.up.railway.app/api/expenses